name: Pylint

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch full history to enable diff comparisons

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: pylint
        run: |
          echo "Finding modified Python files..."
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- '*.py')
          if [ -z "$changed_files" ]; then
            echo "No Python files modified, skipping pylint."
          else
            file_count=$(echo "$changed_files" | wc -w)
            echo "Found $file_count Python file(s) to analyze: $changed_files"
            pylint $changed_files
          fi
